version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: spring
    ports:
      - "8080:8080"
      - "35729:35729"  # Live reload port
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
      - VAADIN_DISABLE_PNPM_CACHE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - spring-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge